### ISSUE TITLE
Custom container failed ‵s local start`. s deploy worked.

### ISSUE THREAD

**Issue by alapha23** [awesome-fc/fc-puppeteer-demo#3]
## Description

Deployment was a success on aliyun when `s local start` doesn't show the image.
Error message on the browser as follows
```
The image "http://localhost:7158/2016-08-15/proxy/puppeteer-customContainer/html2png-customContainer/" cannot be shown because it contains errors.
```

## Steps to reproduce

```
git clone https://github.com/awesome-fc/fc-puppeteer-demo/
cd fc-puppeteer-demo
vim s.yaml #s.yaml as shown below
sudo s build --use-docker
sudo s local start
# then open browser http://localhost:8080
```

## s.yaml

```
edition: 1.0.0
name: transform_fun
access: default
vars:
  region: cn-shenzhen
services:
  fc-puppeteer-customContainer-html2png:
    component: devsapp/fc
    props:
      region: ${vars.region}
      service:
        name: puppeteer-customContainer
        role:
          name: puppeteer-customContainerDefaultRole
          policies:
            - AliyunContainerRegistryReadOnlyAccess
        internetAccess: true
      function:
        name: html2png-customContainer
        description: HTTP function powered by nodejs express
        handler: not-used
        timeout: 60
        caPort: 8080
        memorySize: 1536
        runtime: custom-container
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/puppeteer_namespace/puppeteer_repo:latest
          #command: '[ "node"]'
          #args: '["server.js"]'
        cAPort: 8080
        codeUri: ./
      triggers:
        - name: http-trigger-test
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
```
